version: '3.8'

services:
  consul:
    image: consul
    container_name: consul
    ports:
      - "8500:8500"
    restart: unless-stopped

  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "esdev"
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_LOCAL_CONFIG: '{"backend": {"consul": {"address": "consul:8500", "path": "vault/"}}}'
    depends_on:
      - consul
    restart: unless-stopped
